/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


public class VendorDashboardJF extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VendorDashboardJF.class.getName());
    
    public VendorDashboardJF(){
        this("vendor");
    }

    public VendorDashboardJF(String username) {
        initComponents();
        this.loggedInUsername = username;
        loadVendorProfile();
    }
    private void loadVendorProfile() {
    database.DBOperations db = new database.DBOperations();
    String query = "SELECT * FROM vendors WHERE LOWER(vendor_name) = LOWER(?)";
    try (java.sql.PreparedStatement pst = db.con.prepareStatement(query)) {
        pst.setString(1, loggedInUsername);
        java.sql.ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            nameValueJl.setText(rs.getString("vendor_name"));
            typeValueJL.setText(rs.getString("vendor_type"));
            emailValueJL.setText(rs.getString("vendor_email"));
            locationValueJL.setText(rs.getString("vendor_location"));
            ratingValueJL.setText(rs.getString("vendor_rating") + " / 5");
            boolean active = rs.getBoolean("is_active");
            statusValueJL.setText(active ? "Active" : "Inactive");
        } else {
            nameValueJl.setText("Profile not found for: " + loggedInUsername);
        }
    } catch (java.sql.SQLException e) {
        System.err.println("Profile error: " + e.getMessage());
    }
    db.closeConnection();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJL = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        nameValueJl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        typeValueJL = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        emailValueJL = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        locationValueJL = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        ratingValueJL = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        statusValueJL = new javax.swing.JLabel();
        logoutBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleJL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleJL.setText("Vendor Portal");

        label1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label1.setText("Name");

        nameValueJl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nameValueJl.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Type");

        typeValueJL.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        typeValueJL.setText("jLabel3");

        label3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label3.setText("Email");

        emailValueJL.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        emailValueJL.setText("jLabel1");

        label4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label4.setText("Location");

        locationValueJL.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        locationValueJL.setText("jLabel1");

        label5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label5.setText("Rating");

        ratingValueJL.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ratingValueJL.setText("jLabel1");

        label6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label6.setText("Status");

        statusValueJL.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        statusValueJL.setText("jLabel1");

        logoutBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        logoutBT.setText("Logout");
        logoutBT.addActionListener(this::logoutBTActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label6)
                                        .addGap(90, 90, 90))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(label5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(ratingValueJL))
                            .addComponent(statusValueJL)
                            .addComponent(titleJL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(label4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(locationValueJL))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailValueJL))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(typeValueJL))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label1)
                                    .addGap(87, 87, 87)
                                    .addComponent(nameValueJl)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(logoutBT)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(nameValueJl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeValueJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3)
                    .addComponent(emailValueJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4)
                    .addComponent(locationValueJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5)
                    .addComponent(ratingValueJL))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label6)
                    .addComponent(statusValueJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutBT)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
    new LoginJF().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VendorDashboardJF().setVisible(true));
    }

    private String loggedInUsername;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailValueJL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel locationValueJL;
    private javax.swing.JButton logoutBT;
    private javax.swing.JLabel nameValueJl;
    private javax.swing.JLabel ratingValueJL;
    private javax.swing.JLabel statusValueJL;
    private javax.swing.JLabel titleJL;
    private javax.swing.JLabel typeValueJL;
    // End of variables declaration//GEN-END:variables
}
